//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndromedaServer.WebRole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndromedaServer.WebRole.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannon.
        /// </summary>
        public static string ComponentName_Cannon {
            get {
                return ResourceManager.GetString("ComponentName_Cannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive.
        /// </summary>
        public static string ComponentName_Drive {
            get {
                return ResourceManager.GetString("ComponentName_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sensor.
        /// </summary>
        public static string ComponentName_Sensor {
            get {
                return ResourceManager.GetString("ComponentName_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shield.
        /// </summary>
        public static string ComponentName_Shield {
            get {
                return ResourceManager.GetString("ComponentName_Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown component.
        /// </summary>
        public static string ComponentName_Unknown {
            get {
                return ResourceManager.GetString("ComponentName_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship is already in the targeted star system!.
        /// </summary>
        public static string Error_AlreadyInTargetSystem {
            get {
                return ResourceManager.GetString("Error_AlreadyInTargetSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot attack yourself!.
        /// </summary>
        public static string Error_CannotAttackYourself {
            get {
                return ResourceManager.GetString("Error_CannotAttackYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship is already in space - it cannot be launched again!.
        /// </summary>
        public static string Error_CannotLaunchTwice {
            get {
                return ResourceManager.GetString("Error_CannotLaunchTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any of this component on your ship!.
        /// </summary>
        public static string Error_ComponentNotPresent {
            get {
                return ResourceManager.GetString("Error_ComponentNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid player identifier! Please don&apos;t forget to register yourself on the Andromeda homepage and to enter your identifier in the app.config file!.
        /// </summary>
        public static string Error_InvalidPlayerId {
            get {
                return ResourceManager.GetString("Error_InvalidPlayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ship model!.
        /// </summary>
        public static string Error_InvalidShipModel {
            get {
                return ResourceManager.GetString("Error_InvalidShipModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ship with this transponder code!.
        /// </summary>
        public static string Error_InvalidTransponderCode {
            get {
                return ResourceManager.GetString("Error_InvalidTransponderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reached the modification limit - move to another star system to add or remove further components!.
        /// </summary>
        public static string Error_ModificationLimitReached {
            get {
                return ResourceManager.GetString("Error_ModificationLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot trade a negative quantity!.
        /// </summary>
        public static string Error_NoNegativeQuantity {
            get {
                return ResourceManager.GetString("Error_NoNegativeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This star system are not interested in this commodity!.
        /// </summary>
        public static string Error_NotBoughtHere {
            get {
                return ResourceManager.GetString("Error_NotBoughtHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough cargo space in your ship for this order!.
        /// </summary>
        public static string Error_NotEnoughCargoSpace {
            get {
                return ResourceManager.GetString("Error_NotEnoughCargoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity available of this commodity in this star system is less than the amount you tried to purchase!.
        /// </summary>
        public static string Error_NotEnoughForSale {
            get {
                return ResourceManager.GetString("Error_NotEnoughForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity stored of this commodity in your cargo hold is less than the amount you tried to sell!.
        /// </summary>
        public static string Error_NotEnoughInHold {
            get {
                return ResourceManager.GetString("Error_NotEnoughInHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0} credits to purchase this ship model!.
        /// </summary>
        public static string Error_NotEnoughMoneyForShipModel {
            get {
                return ResourceManager.GetString("Error_NotEnoughMoneyForShipModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0} credits to purchase another ship!.
        /// </summary>
        public static string Error_NotEnoughMoneyForShipPurchase {
            get {
                return ResourceManager.GetString("Error_NotEnoughMoneyForShipPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough money to perform this purchase!.
        /// </summary>
        public static string Error_NotEnoughMoneyForTrade {
            get {
                return ResourceManager.GetString("Error_NotEnoughMoneyForTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough free cargo hold space for this component!.
        /// </summary>
        public static string Error_NotEnoughSpaceForComponent {
            get {
                return ResourceManager.GetString("Error_NotEnoughSpaceForComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t this commodity in your cargo hold!.
        /// </summary>
        public static string Error_NotInHold {
            get {
                return ResourceManager.GetString("Error_NotInHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This star system does not trade this commodity!.
        /// </summary>
        public static string Error_NotTradedHere {
            get {
                return ResourceManager.GetString("Error_NotTradedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ship was created recently, wait a little!.
        /// </summary>
        public static string Error_ShipCreatedRecently {
            get {
                return ResourceManager.GetString("Error_ShipCreatedRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship is currently in space - this operation cannot be performed!.
        /// </summary>
        public static string Error_ShipIsInSpace {
            get {
                return ResourceManager.GetString("Error_ShipIsInSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reached the maximum number of ships!.
        /// </summary>
        public static string Error_ShipLimitReached {
            get {
                return ResourceManager.GetString("Error_ShipLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a ship model that is equal to or better than the one you tried to purchase!.
        /// </summary>
        public static string Error_ShipModelAlreadyBetter {
            get {
                return ResourceManager.GetString("Error_ShipModelAlreadyBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is out of range!.
        /// </summary>
        public static string Error_ShipOutOfRange {
            get {
                return ResourceManager.GetString("Error_ShipOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ship was raided recently, wait a little!.
        /// </summary>
        public static string Error_ShipRaidedRecently {
            get {
                return ResourceManager.GetString("Error_ShipRaidedRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target star is too far from the ship!.
        /// </summary>
        public static string Error_StarIsTooFar {
            get {
                return ResourceManager.GetString("Error_StarIsTooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the following cargo in your hold:&lt;br /&gt;{0}.
        /// </summary>
        public static string FleetInfo_CargoHeader {
            get {
                return ResourceManager.GetString("FleetInfo_CargoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} units&lt;br /&gt;.
        /// </summary>
        public static string FleetInfo_CargoItem {
            get {
                return ResourceManager.GetString("FleetInfo_CargoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship&apos;s free cargo capacity is {0} units (out of the maximum {1} units), its maximum speed is {2} light years/minute and its sensor range is {3} light years.&lt;br /&gt;Besides its built-in systems it has {4} extra drives, {5} extra sensors, {6} cannons and {7} shields installed..
        /// </summary>
        public static string FleetInfo_Hardware {
            get {
                return ResourceManager.GetString("FleetInfo_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship has no cargo..
        /// </summary>
        public static string FleetInfo_NoCargo {
            get {
                return ResourceManager.GetString("FleetInfo_NoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ship is currently in flight.&lt;br /&gt;Origin: &lt;b&gt;{0}&lt;/b&gt;&lt;br /&gt;Destination: &lt;b&gt;{1}&lt;/b&gt;&lt;br /&gt;The distance between the two stars is {2} light years. The ship is {3} light years from its destination..
        /// </summary>
        public static string FleetInfo_ShipEnRoute {
            get {
                return ResourceManager.GetString("FleetInfo_ShipEnRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ship is currently in the main spaceport of the &lt;b&gt;{0}&lt;/b&gt; star system..
        /// </summary>
        public static string FleetInfo_ShipInPort {
            get {
                return ResourceManager.GetString("FleetInfo_ShipInPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hr /&gt;Ship {0}&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        public static string FleetInfo_ShipN {
            get {
                return ResourceManager.GetString("FleetInfo_ShipN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;b&gt;{0}&lt;/b&gt; credits and {1} ships..
        /// </summary>
        public static string FleetInfo_ShipsAndCredits {
            get {
                return ResourceManager.GetString("FleetInfo_ShipsAndCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;The extra drives, sensors, cannons and shields occupy {0} units of space in your cargo hold..
        /// </summary>
        public static string FleetInfo_SpaceOccupiedByComponents {
            get {
                return ResourceManager.GetString("FleetInfo_SpaceOccupiedByComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}: {2} credits&lt;br /&gt;.
        /// </summary>
        public static string LeaderboardItem {
            get {
                return ResourceManager.GetString("LeaderboardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} launched from {1} to {2}..
        /// </summary>
        public static string Log_Launch {
            get {
                return ResourceManager.GetString("Log_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attacked {1}, but couldn&apos;t penetrate the target&apos;s shields and was forced to retreat!.
        /// </summary>
        public static string Log_PirateRaid_Failed {
            get {
                return ResourceManager.GetString("Log_PirateRaid_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attacked {1} and robbed him of {2} units of cargo!.
        /// </summary>
        public static string Log_PirateRaid_Successful {
            get {
                return ResourceManager.GetString("Log_PirateRaid_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} was {1} {2} {3}&apos;s ship. There are now {4} installed..
        /// </summary>
        public static string Log_ShipModification {
            get {
                return ResourceManager.GetString("Log_ShipModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added.
        /// </summary>
        public static string Log_ShipModification_Added {
            get {
                return ResourceManager.GetString("Log_ShipModification_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string Log_ShipModification_FromShip {
            get {
                return ResourceManager.GetString("Log_ShipModification_FromShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed.
        /// </summary>
        public static string Log_ShipModification_Removed {
            get {
                return ResourceManager.GetString("Log_ShipModification_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Log_ShipModification_ToShip {
            get {
                return ResourceManager.GetString("Log_ShipModification_ToShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} purchased a new spaceship - the fleet now includes {1} ships!.
        /// </summary>
        public static string Log_ShipPurchase {
            get {
                return ResourceManager.GetString("Log_ShipPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s ship was upgraded to the {1} model (cargo space: {2} units)!.
        /// </summary>
        public static string Log_ShipUpgrade {
            get {
                return ResourceManager.GetString("Log_ShipUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tried to {1} zero units of {2}..
        /// </summary>
        public static string Log_Trade_Failed {
            get {
                return ResourceManager.GetString("Log_Trade_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string Log_Trade_Failed_Buy {
            get {
                return ResourceManager.GetString("Log_Trade_Failed_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sell.
        /// </summary>
        public static string Log_Trade_Failed_Sell {
            get {
                return ResourceManager.GetString("Log_Trade_Failed_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} units of {3} in {4}, for {5} credits apiece. {0} now has {6} credits..
        /// </summary>
        public static string Log_Trade_Successful {
            get {
                return ResourceManager.GetString("Log_Trade_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bought.
        /// </summary>
        public static string Log_Trade_Successful_Bought {
            get {
                return ResourceManager.GetString("Log_Trade_Successful_Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sold.
        /// </summary>
        public static string Log_Trade_Successful_Sold {
            get {
                return ResourceManager.GetString("Log_Trade_Successful_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened!.
        /// </summary>
        public static string Log_Unknown {
            get {
                return ResourceManager.GetString("Log_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover the mouse over something!.
        /// </summary>
        public static string Map_HoverMouse {
            get {
                return ResourceManager.GetString("Map_HoverMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaceship: .
        /// </summary>
        public static string Map_Spaceship {
            get {
                return ResourceManager.GetString("Map_Spaceship", resourceCulture);
            }
        }
    }
}
