//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndromedaScaffold.WorkerRole.AndromedaServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Spaceship", Namespace="http://schemas.datacontract.org/2004/07/Andromeda.ClientEntities")]
    public partial class Spaceship : object
    {
        
        private int CannonCountField;
        
        private AndromedaScaffold.WorkerRole.AndromedaServiceReference.CommodityInHold[] CargoField;
        
        private int DriveCountField;
        
        private int FreeCapacityField;
        
        private bool IsInTransitField;
        
        private System.DateTime LastRaidedField;
        
        private int ModificationsRemainingField;
        
        private long MoneyField;
        
        private int SensorCountField;
        
        private double SensorRangeInLightYearsField;
        
        private int ShieldCountField;
        
        private double SpeedInLightYearsPerMinuteField;
        
        private int TotalCapacityField;
        
        private int TotalShipsOwnedByPlayerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CannonCount
        {
            get
            {
                return this.CannonCountField;
            }
            set
            {
                this.CannonCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AndromedaScaffold.WorkerRole.AndromedaServiceReference.CommodityInHold[] Cargo
        {
            get
            {
                return this.CargoField;
            }
            set
            {
                this.CargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriveCount
        {
            get
            {
                return this.DriveCountField;
            }
            set
            {
                this.DriveCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FreeCapacity
        {
            get
            {
                return this.FreeCapacityField;
            }
            set
            {
                this.FreeCapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInTransit
        {
            get
            {
                return this.IsInTransitField;
            }
            set
            {
                this.IsInTransitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastRaided
        {
            get
            {
                return this.LastRaidedField;
            }
            set
            {
                this.LastRaidedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModificationsRemaining
        {
            get
            {
                return this.ModificationsRemainingField;
            }
            set
            {
                this.ModificationsRemainingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Money
        {
            get
            {
                return this.MoneyField;
            }
            set
            {
                this.MoneyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SensorCount
        {
            get
            {
                return this.SensorCountField;
            }
            set
            {
                this.SensorCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SensorRangeInLightYears
        {
            get
            {
                return this.SensorRangeInLightYearsField;
            }
            set
            {
                this.SensorRangeInLightYearsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShieldCount
        {
            get
            {
                return this.ShieldCountField;
            }
            set
            {
                this.ShieldCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SpeedInLightYearsPerMinute
        {
            get
            {
                return this.SpeedInLightYearsPerMinuteField;
            }
            set
            {
                this.SpeedInLightYearsPerMinuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCapacity
        {
            get
            {
                return this.TotalCapacityField;
            }
            set
            {
                this.TotalCapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalShipsOwnedByPlayer
        {
            get
            {
                return this.TotalShipsOwnedByPlayerField;
            }
            set
            {
                this.TotalShipsOwnedByPlayerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommodityInHold", Namespace="http://schemas.datacontract.org/2004/07/Andromeda.ClientEntities")]
    public partial class CommodityInHold : object
    {
        
        private string NameField;
        
        private int StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Star", Namespace="http://schemas.datacontract.org/2004/07/Andromeda.ClientEntities")]
    public partial class Star : object
    {
        
        private AndromedaScaffold.WorkerRole.AndromedaServiceReference.CommodityAtStar[] CommoditiesField;
        
        private double DistanceInLightYearsField;
        
        private string NameField;
        
        private System.Guid StarGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AndromedaScaffold.WorkerRole.AndromedaServiceReference.CommodityAtStar[] Commodities
        {
            get
            {
                return this.CommoditiesField;
            }
            set
            {
                this.CommoditiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DistanceInLightYears
        {
            get
            {
                return this.DistanceInLightYearsField;
            }
            set
            {
                this.DistanceInLightYearsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StarGuid
        {
            get
            {
                return this.StarGuidField;
            }
            set
            {
                this.StarGuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommodityAtStar", Namespace="http://schemas.datacontract.org/2004/07/Andromeda.ClientEntities")]
    public partial class CommodityAtStar : object
    {
        
        private string NameField;
        
        private int PriceField;
        
        private int StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerchantShip", Namespace="http://schemas.datacontract.org/2004/07/Andromeda.ClientEntities")]
    public partial class MerchantShip : object
    {
        
        private double DistanceField;
        
        private System.Guid TransponderCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TransponderCode
        {
            get
            {
                return this.TransponderCodeField;
            }
            set
            {
                this.TransponderCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AndromedaScaffold.WorkerRole.AndromedaServiceReference.IAndromedaService")]
    public interface IAndromedaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/GetSpaceshipStatus", ReplyAction="http://tempuri.org/IAndromedaService/GetSpaceshipStatusResponse")]
        System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.Spaceship> GetSpaceshipStatusAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/GetCurrentStar", ReplyAction="http://tempuri.org/IAndromedaService/GetCurrentStarResponse")]
        System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.Star> GetCurrentStarAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/GetVisibleStars", ReplyAction="http://tempuri.org/IAndromedaService/GetVisibleStarsResponse")]
        System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.Star[]> GetVisibleStarsAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/GetRaidableShips", ReplyAction="http://tempuri.org/IAndromedaService/GetRaidableShipsResponse")]
        System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.MerchantShip[]> GetRaidableShipsAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/GetOwnedShips", ReplyAction="http://tempuri.org/IAndromedaService/GetOwnedShipsResponse")]
        System.Threading.Tasks.Task<System.Guid[]> GetOwnedShipsAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/RegisterRunLocation", ReplyAction="http://tempuri.org/IAndromedaService/RegisterRunLocationResponse")]
        System.Threading.Tasks.Task RegisterRunLocationAsync(System.Guid playerGuid, bool isEmulator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/LaunchSpaceship", ReplyAction="http://tempuri.org/IAndromedaService/LaunchSpaceshipResponse")]
        System.Threading.Tasks.Task LaunchSpaceshipAsync(System.Guid playerGuid, System.Guid starGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/Buy", ReplyAction="http://tempuri.org/IAndromedaService/BuyResponse")]
        System.Threading.Tasks.Task BuyAsync(System.Guid playerGuid, string commodityName, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/BuyMaximum", ReplyAction="http://tempuri.org/IAndromedaService/BuyMaximumResponse")]
        System.Threading.Tasks.Task BuyMaximumAsync(System.Guid playerGuid, string commodityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/Sell", ReplyAction="http://tempuri.org/IAndromedaService/SellResponse")]
        System.Threading.Tasks.Task SellAsync(System.Guid playerGuid, string commodityName, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/AddSensor", ReplyAction="http://tempuri.org/IAndromedaService/AddSensorResponse")]
        System.Threading.Tasks.Task AddSensorAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/RemoveSensor", ReplyAction="http://tempuri.org/IAndromedaService/RemoveSensorResponse")]
        System.Threading.Tasks.Task RemoveSensorAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/AddDrive", ReplyAction="http://tempuri.org/IAndromedaService/AddDriveResponse")]
        System.Threading.Tasks.Task AddDriveAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/RemoveDrive", ReplyAction="http://tempuri.org/IAndromedaService/RemoveDriveResponse")]
        System.Threading.Tasks.Task RemoveDriveAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/UpgradeShip", ReplyAction="http://tempuri.org/IAndromedaService/UpgradeShipResponse")]
        System.Threading.Tasks.Task UpgradeShipAsync(System.Guid playerGuid, int modelType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/AddCannon", ReplyAction="http://tempuri.org/IAndromedaService/AddCannonResponse")]
        System.Threading.Tasks.Task AddCannonAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/RemoveCannon", ReplyAction="http://tempuri.org/IAndromedaService/RemoveCannonResponse")]
        System.Threading.Tasks.Task RemoveCannonAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/AddShield", ReplyAction="http://tempuri.org/IAndromedaService/AddShieldResponse")]
        System.Threading.Tasks.Task AddShieldAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/RemoveShield", ReplyAction="http://tempuri.org/IAndromedaService/RemoveShieldResponse")]
        System.Threading.Tasks.Task RemoveShieldAsync(System.Guid playerGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/Raid", ReplyAction="http://tempuri.org/IAndromedaService/RaidResponse")]
        System.Threading.Tasks.Task RaidAsync(System.Guid playerGuid, System.Guid transponderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAndromedaService/BuyNewShip", ReplyAction="http://tempuri.org/IAndromedaService/BuyNewShipResponse")]
        System.Threading.Tasks.Task BuyNewShipAsync(System.Guid playerGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface IAndromedaServiceChannel : AndromedaScaffold.WorkerRole.AndromedaServiceReference.IAndromedaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class AndromedaServiceClient : System.ServiceModel.ClientBase<AndromedaScaffold.WorkerRole.AndromedaServiceReference.IAndromedaService>, AndromedaScaffold.WorkerRole.AndromedaServiceReference.IAndromedaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AndromedaServiceClient() : 
                base(AndromedaServiceClient.GetDefaultBinding(), AndromedaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAndromedaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AndromedaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AndromedaServiceClient.GetBindingForEndpoint(endpointConfiguration), AndromedaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AndromedaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AndromedaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AndromedaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AndromedaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AndromedaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.Spaceship> GetSpaceshipStatusAsync(System.Guid playerGuid)
        {
            return base.Channel.GetSpaceshipStatusAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.Star> GetCurrentStarAsync(System.Guid playerGuid)
        {
            return base.Channel.GetCurrentStarAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.Star[]> GetVisibleStarsAsync(System.Guid playerGuid)
        {
            return base.Channel.GetVisibleStarsAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task<AndromedaScaffold.WorkerRole.AndromedaServiceReference.MerchantShip[]> GetRaidableShipsAsync(System.Guid playerGuid)
        {
            return base.Channel.GetRaidableShipsAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task<System.Guid[]> GetOwnedShipsAsync(System.Guid playerGuid)
        {
            return base.Channel.GetOwnedShipsAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task RegisterRunLocationAsync(System.Guid playerGuid, bool isEmulator)
        {
            return base.Channel.RegisterRunLocationAsync(playerGuid, isEmulator);
        }
        
        public System.Threading.Tasks.Task LaunchSpaceshipAsync(System.Guid playerGuid, System.Guid starGuid)
        {
            return base.Channel.LaunchSpaceshipAsync(playerGuid, starGuid);
        }
        
        public System.Threading.Tasks.Task BuyAsync(System.Guid playerGuid, string commodityName, int quantity)
        {
            return base.Channel.BuyAsync(playerGuid, commodityName, quantity);
        }
        
        public System.Threading.Tasks.Task BuyMaximumAsync(System.Guid playerGuid, string commodityName)
        {
            return base.Channel.BuyMaximumAsync(playerGuid, commodityName);
        }
        
        public System.Threading.Tasks.Task SellAsync(System.Guid playerGuid, string commodityName, int quantity)
        {
            return base.Channel.SellAsync(playerGuid, commodityName, quantity);
        }
        
        public System.Threading.Tasks.Task AddSensorAsync(System.Guid playerGuid)
        {
            return base.Channel.AddSensorAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task RemoveSensorAsync(System.Guid playerGuid)
        {
            return base.Channel.RemoveSensorAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task AddDriveAsync(System.Guid playerGuid)
        {
            return base.Channel.AddDriveAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task RemoveDriveAsync(System.Guid playerGuid)
        {
            return base.Channel.RemoveDriveAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task UpgradeShipAsync(System.Guid playerGuid, int modelType)
        {
            return base.Channel.UpgradeShipAsync(playerGuid, modelType);
        }
        
        public System.Threading.Tasks.Task AddCannonAsync(System.Guid playerGuid)
        {
            return base.Channel.AddCannonAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task RemoveCannonAsync(System.Guid playerGuid)
        {
            return base.Channel.RemoveCannonAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task AddShieldAsync(System.Guid playerGuid)
        {
            return base.Channel.AddShieldAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task RemoveShieldAsync(System.Guid playerGuid)
        {
            return base.Channel.RemoveShieldAsync(playerGuid);
        }
        
        public System.Threading.Tasks.Task RaidAsync(System.Guid playerGuid, System.Guid transponderCode)
        {
            return base.Channel.RaidAsync(playerGuid, transponderCode);
        }
        
        public System.Threading.Tasks.Task BuyNewShipAsync(System.Guid playerGuid)
        {
            return base.Channel.BuyNewShipAsync(playerGuid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAndromedaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAndromedaService))
            {
                return new System.ServiceModel.EndpointAddress("http://ifat.azurewebsites.net/AndromedaService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AndromedaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAndromedaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AndromedaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAndromedaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAndromedaService,
        }
    }
}
